import Head from 'next/head'

import Information from './Information';
import Relations from './Relations';




export default function Personaje({ datos }) {

    const { results } = datos
    const datosPersonaje = results[0];


    const { comics, series, stories } = datosPersonaje

    return (
        <>
            <Head>
                <title>{datosPersonaje.name} | Marvel API</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Information datosPersonaje={datosPersonaje} />
            <Relations comics={comics} series={series} stories={stories} />


        </>
    )
}