import Head from 'next/head'

import Information from './Information';
import Relations from './Relations';




export default function Comics({ datos }) {

    const { results } = datos
    const datosCreador = results[0];

    const { comics, series, stories } = datosCreador

    console.log(stories);

    return (
        <>
            <Head>
                <title>{datosCreador.firstName} | Marvel API</title>
                <meta name="description" content="Generated by create next app" />
            </Head>


            <Information datos={datosCreador} />
            <Relations stories={stories} comics={comics} series={series} />

        </>
    )
}