import Head from 'next/head'
import getHashParam from 'services/getHashParam'

import getRandomVariant from 'config/getRandomVariant';

import List from 'components/Comics/List';

export default function Index(props) {

    return (
        <>
            <Head>
                <title>Comics | Marvel API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter"
                    rel="stylesheet"
                />
            </Head>

            <List images={getRandomVariant(props.results, 15)} />


        </>
    )
}

export async function getServerSideProps(context) {
    const search = 'comics';
    const limit = 20;
    const url = getHashParam({ search, limit })
    return fetch(url).
        then(res => res.json()).
        then(data => {

            return {
                props: data.data
            }
        });


}
