import Head from 'next/head'
import getHashParam from 'services/getHashParam'

import getRandomVariant from 'config/getRandomVariant';

import List from 'components/Creador/List';
import { getSession } from 'next-auth/client'


export default function Index(props) {

    return (
        <>
            <Head>
                <title>Creadores | Marvel API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter"
                    rel="stylesheet"
                />
            </Head>

            <List images={getRandomVariant(props.results, 15)} />


        </>
    )

}

export async function getServerSideProps(context) {
    const { req, res } = context

    const session = await getSession(req)

    if (!session) {
        res.writeHead(307, { Location: '/' });
        res.end()
        return { props: {} };
    }

    const search = 'creators';
    const limit = 20;
    const url = getHashParam({ search, limit })
    return fetch(url).
        then(res => res.json()).
        then(data => {

            return {
                props: data.data
            }
        });


}
