import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/client'

import getHashParam from 'services/getHashParam'
import getRandomVariant from 'config/getRandomVariant';


import ListPersonajes from 'components/Personaje/List';
import ListComics from 'components/Comics/List';

export default function Home(props) {
  const [session, loading] = useSession();

  console.log(session);
  const { dataCharacters, dataComics } = props


  return (
    <>
      <Head>
        <title>Inicio | Marvel API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter"
          rel="stylesheet"
        />
      </Head>

      <ListPersonajes images={getRandomVariant(dataCharacters.results, 4)} />
      <ListComics images={getRandomVariant(dataComics.results, 4)} />


    </>
  )
}

export async function getServerSideProps(context) {
  const getCharacters = async () => {
    const search = 'characters';
    const limit = 20;
    const url = getHashParam({ search, limit })
    return fetch(url).
      then(res => res.json()).
      then(data => {
        return data.data;
      })
  }

  const getComics = async () => {
    const search = 'comics';
    const limit = 20;
    const url = getHashParam({ search, limit })
    return fetch(url).
      then(res => res.json()).
      then(data => {
        return data.data;
      })
  }


  const dataCharacters = await getCharacters();
  const dataComics = await getComics();

  return {
    props: { dataCharacters, dataComics }
  }


}
