import Head from 'next/head'

import Information from './Information';
import Relations from './Relations';




export default function Comics({ datos }) {

    const { results } = datos
    const datosComics = results[0];

    console.log(datosComics);

    const { characters, stories } = datosComics

    console.log(stories);

    return (
        <>
            <Head>
                <title>{datosComics.title} | Marvel API</title>
                <meta name="description" content="Generated by create next app" />
            </Head>


            <Information datos={datosComics} />
            <Relations stories={stories} characters={characters} />

        </>
    )
}